services:
  eureka-server:
    restart: unless-stopped
    platform: linux/amd64
    build: services/eureka-server
    ports:
      - "9000:9000"
  gateway-service:
    restart: unless-stopped
    platform: linux/amd64
    build: services/gateway-service
    ports:
      - "8080:8080"
  example-service:
    restart: unless-stopped
    platform: linux/amd64
    build: services/example-service